[package]
name = "helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
# Local
exploit-program = { path = "../program" }

# EVM
alloy.workspace = true
alloy.features = ["rpc-types"]
alloy-json-abi = { version = "0.7.6", default-features = false }
alloy-signer-local = { version = "0.2.1", default-features = false }
anvil.workspace = true
revm-interpreter.workspace = true
revm.workspace = true

# Misc
eyre.workspace = true
lazy_static = "1.5.0"
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
bincode = "1.3.3"

