[package]
name = "prove-exploit"
version = "0.1.0"
edition = "2021"

[dependencies]
# Local
common = { path = "../common" }

# Sp1
sp1-sdk.workspace = true
sp1-zkvm.workspace = true

# EVM
alloy.workspace = true
alloy.features = ["rpc-types"]
alloy-json-abi = { version = "0.7.6", default-features = false }
alloy-signer-local = { version = "0.2.1", default-features = false }
alloy-signer = { version = "0.2.1", default-features = false }
anvil.workspace = true
revm-interpreter.workspace = true
revm.workspace = true
reth-primitives.workspace = true

# Misc
bincode.workspace = true
clap.workspace = true
eyre.workspace = true
lazy_static = "1.5.0"
serde_json.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[dev-dependencies]
rand = "0.8.5"

[build-dependencies]
sp1-helper = "1.1.0"