[workspace]
resolver = "2"

members = [
  "helpers",
  "program",
  "bin"
]

[workspace.dependencies]
alloy = { version = "0.2.1", default-features = false }
anvil = { git = "https://github.com/foundry-rs/foundry.git", package = "anvil", version = "0.2.0" }
clap = { version = "4.5.15", features = ["derive"] }
eyre = "0.6.12"
revm-interpreter = { version = "9.0.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", rev = "v1.0.8-testnet" }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.8-testnet" }
tokio = { version = "1.39.2", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"

