[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
# EVM
alloy.workspace = true
alloy.features = ["rpc-types"]
revm-interpreter.workspace = true

# Misc
serde.workspace = true