[package]
version = "0.1.0"
name = "exploit-program"
edition = "2021"

[dependencies]
# Sp1
sp1-zkvm.workspace = true

# EVM
alloy.workspace = true
alloy.features = ["rpc-types"]
revm-interpreter.workspace = true
revm.workspace = true

# Misc
bincode.workspace = true
eyre.workspace = true
serde.workspace = true